select * from Information_Allied_Characters;
select * from Inventory_Allied_Characters;
select * from lunatic_Occultist;
select * from lunatic_Occultist_Drop;
select * from Pilars;
select* from Solar_pilar_Enemies;
select* from Vortex_pilar_Enemies;
select* from Nebulla_pilar_Enemies;
select* from Stardust_pilar_Enemies;
select* from MoonLord;
select* from MoonLord_Drop;